-- Scent & Sense Backend — Postgres schema (Supabase compatible)
-- v6.0.0 (Apr 2026)
--
-- Run once against your Supabase / Postgres database:
--   psql "$DATABASE_URL" -f migrations/001_init.sql
-- or: npm run migrate
--
-- Design notes:
--   • Primary keys are TEXT with a uuid default. Using TEXT (not uuid)
--     lets existing ESP32 boards keep their Mongo ObjectId identity
--     (e.g. "69d27f3e3820c6a70d12c508" is still a valid id) while new
--     records generated by the backend get real UUIDs.
--   • Schedule is kept on the device row as JSONB (was an embedded
--     sub-document in Mongo). Indexed only if needed.
--   • Per-user notification read state is a normalized join table
--     (notification_reads), replacing the readBy array on Mongo.
--   • fcm_tokens is new for v6.0 — one row per device FCM token.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

-- ─── Utility trigger for updated_at ──────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── users ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name        TEXT NOT NULL,
  email       TEXT NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'technician'
              CHECK (role IN ('admin','manager','technician')),
  last_login  TIMESTAMPTZ,
  is_online   BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS users_updated_at ON users;
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── customers ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id             TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name           TEXT NOT NULL,
  contact_name   TEXT NOT NULL DEFAULT '',
  contact_phone  TEXT NOT NULL DEFAULT '',
  contact_email  TEXT NOT NULL DEFAULT '',
  address        TEXT NOT NULL DEFAULT '',
  package_qty    INTEGER NOT NULL DEFAULT 0,
  notes          TEXT NOT NULL DEFAULT '',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS customers_updated_at ON customers;
CREATE TRIGGER customers_updated_at BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── devices ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS devices (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  serial_number       TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL DEFAULT '',
  ip                  TEXT NOT NULL DEFAULT '',
  mac                 TEXT NOT NULL DEFAULT '',
  hardware_id         TEXT NOT NULL DEFAULT '',
  hardware_model      TEXT NOT NULL DEFAULT 'ESP32 Diffuser',
  customer_id         TEXT REFERENCES customers(id) ON DELETE SET NULL,
  location            TEXT NOT NULL DEFAULT '',
  group_id            TEXT,
  status              TEXT NOT NULL DEFAULT 'offline'
                      CHECK (status IN ('online','offline','error')),
  is_on               BOOLEAN NOT NULL DEFAULT false,
  level               INTEGER NOT NULL DEFAULT 100 CHECK (level BETWEEN 0 AND 100),
  level_ml            INTEGER,
  installed_tank_ml   INTEGER NOT NULL DEFAULT 1000,
  scent_name          TEXT NOT NULL DEFAULT '',
  battery             INTEGER NOT NULL DEFAULT 100 CHECK (battery BETWEEN 0 AND 100),
  battery_voltage     NUMERIC,
  battery_status      TEXT NOT NULL DEFAULT 'unknown'
                      CHECK (battery_status IN ('charging','discharging','full','unknown')),
  pump_ok             BOOLEAN NOT NULL DEFAULT true,
  relay_ok            BOOLEAN NOT NULL DEFAULT true,
  wifi_ssid           TEXT NOT NULL DEFAULT '',
  wifi_ip             TEXT NOT NULL DEFAULT '',
  signal_strength     INTEGER,
  bt_address          TEXT NOT NULL DEFAULT '',
  bt_connected        BOOLEAN NOT NULL DEFAULT false,
  schedule            JSONB NOT NULL DEFAULT '[]'::jsonb,
  firmware_version    TEXT NOT NULL DEFAULT '1.0.0',
  device_token        TEXT NOT NULL DEFAULT '',
  claim_code          TEXT NOT NULL DEFAULT '',
  command_version     INTEGER NOT NULL DEFAULT 0,
  last_command_at     TIMESTAMPTZ,
  provisioned_at      TIMESTAMPTZ,
  last_sensor_update  TIMESTAMPTZ,
  last_seen_at        TIMESTAMPTZ,
  notes               TEXT NOT NULL DEFAULT '',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_devices_customer         ON devices(customer_id);
CREATE INDEX IF NOT EXISTS idx_devices_status           ON devices(status);
CREATE INDEX IF NOT EXISTS idx_devices_customer_status  ON devices(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_devices_customer_level   ON devices(customer_id, level);
CREATE INDEX IF NOT EXISTS idx_devices_customer_created ON devices(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen        ON devices(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_devices_last_sensor      ON devices(last_sensor_update);
CREATE INDEX IF NOT EXISTS idx_devices_mac              ON devices(mac);
CREATE INDEX IF NOT EXISTS idx_devices_hardware_id      ON devices(hardware_id);
CREATE INDEX IF NOT EXISTS idx_devices_wifi_ssid        ON devices(wifi_ssid);

DROP TRIGGER IF EXISTS devices_updated_at ON devices;
CREATE TRIGGER devices_updated_at BEFORE UPDATE ON devices
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── service_logs ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS service_logs (
  id             TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  device_id      TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  technician_id  TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  type           TEXT NOT NULL
                 CHECK (type IN ('refill','repair','inspection','installation','uninstall','other')),
  description    TEXT NOT NULL DEFAULT '',
  notes          TEXT NOT NULL DEFAULT '',
  photos         JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_service_logs_device      ON service_logs(device_id);
CREATE INDEX IF NOT EXISTS idx_service_logs_technician  ON service_logs(technician_id);
CREATE INDEX IF NOT EXISTS idx_service_logs_created     ON service_logs(created_at DESC);

DROP TRIGGER IF EXISTS service_logs_updated_at ON service_logs;
CREATE TRIGGER service_logs_updated_at BEFORE UPDATE ON service_logs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── notifications ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  title         TEXT NOT NULL,
  message       TEXT NOT NULL,
  type          TEXT NOT NULL DEFAULT 'info',
  device_id     TEXT REFERENCES devices(id) ON DELETE SET NULL,
  device_name   TEXT NOT NULL DEFAULT '',
  target_roles  JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_type_created
  ON notifications(type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_device_type_created
  ON notifications(device_id, type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_created
  ON notifications(created_at DESC);

DROP TRIGGER IF EXISTS notifications_updated_at ON notifications;
CREATE TRIGGER notifications_updated_at BEFORE UPDATE ON notifications
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── notification_reads (per-user read state) ───────────────
CREATE TABLE IF NOT EXISTS notification_reads (
  notification_id  TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (notification_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_reads_user ON notification_reads(user_id);

-- ─── fcm_tokens ──────────────────────────────────────────────
-- One row per Firebase Cloud Messaging registration token.
-- Tokens can move between users on the same device (e.g. after logout
-- + login on a shared tablet), so user_id is not part of the primary
-- key. We upsert on token.
CREATE TABLE IF NOT EXISTS fcm_tokens (
  token       TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform    TEXT NOT NULL DEFAULT 'android',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fcm_tokens_user ON fcm_tokens(user_id);

DROP TRIGGER IF EXISTS fcm_tokens_updated_at ON fcm_tokens;
CREATE TRIGGER fcm_tokens_updated_at BEFORE UPDATE ON fcm_tokens
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
